# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 16:56
from __future__ import unicode_literals

import comics.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic_name', models.CharField(max_length=500)),
                ('comic_description', models.TextField(max_length=4000)),
                ('comic_author', models.CharField(blank=True, max_length=250)),
                ('comic_artist', models.CharField(blank=True, max_length=250)),
                ('comic_genre', models.CharField(max_length=100)),
                ('comic_total_chapters', models.CharField(default='Unknown', max_length=100)),
                ('comic_type', models.CharField(default='Comic', max_length=100)),
                ('comic_status', models.CharField(default='Ongoing', max_length=100)),
                ('comic_original_name', models.CharField(blank=True, default='None', max_length=100)),
                ('comic_image', models.FileField(help_text='Please upload a cover with minimum dimensions of 500px X 500px', upload_to=comics.models.comic_upload_location)),
                ('comic_banner_image', models.FileField(blank=True, help_text='1500px by 500px is recommended. This is an optional field (for now)', upload_to=comics.models.comic_banner_upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='ComicChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(max_length=1000)),
                ('chapter_number', models.CharField(max_length=1000)),
                ('chapter_volume', models.CharField(blank=True, default=0, max_length=1000)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('chapter_images', models.TextField(help_text='Just enter the ID of the Imgur Album and not the full URL.', max_length=20)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.Comic')),
            ],
        ),
    ]
